-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    user_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    description text,
    phone_number text NOT NULL,
    location_id bigint,
    group_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Locations"
(
    location_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    geo_longitude numeric(9,6),
    geo_latitude numeric(9,6),
    radius bigint,
    address text

    CONSTRAINT check_locations
    CHECK (
        address IS NOT NULL
        OR
        (geo_longitude IS NOT NULL AND geo_latitude IS NOT NULL AND radius IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public."Available_Weekdays"
(
    available_weekends_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    weekday text NOT NULL,
    operator_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Weekdays"
(
    weekday text NOT NULL,
    PRIMARY KEY (weekday)
);

CREATE TABLE IF NOT EXISTS public."Groups"
(
    group_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    client boolean NOT NULL,
    operator boolean NOT NULL,
    admin boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Matches"
(
    match_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    operator_id bigint NOT NULL,
    offer_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Offers"
(
    offer_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    location_id bigint NOT NULL,
    client_id bigint NOT NULL,
    match_id bigint,
    offer_type text NOT NULL,
    description text NOT NULL,
    deadline_date date NOT NULL,
    status text NOT NULL,
    format text,
    flight_date date,
    operator_rating smallint CHECK (operator_rating BETWEEN 1 AND 5),
    operator_review text,
    client_rating smallint CHECK (client_rating BETWEEN 1 AND 5),
    client_review text
);

CREATE TABLE IF NOT EXISTS public."Offer_Parameters"
(
    offer_parameters_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    offer_id bigint NOT NULL,
    parameter_id text NOT NULL,
    value text NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Parameters"
(
    name text NOT NULL,
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public."Type_Parameters"
(
    type_name text NOT NULL,
    parameter_name text NOT NULL,
     PRIMARY KEY (type_name, parameter_name)
);

CREATE TABLE IF NOT EXISTS public."Offer_Types"
(
    name text NOT NULL,
    PRIMARY KEY (name)
);

ALTER TABLE IF EXISTS public."Users"
    ADD FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Users"
    ADD FOREIGN KEY (group_id)
    REFERENCES public."Groups" (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Available_Weekdays"
    ADD FOREIGN KEY (operator_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Available_Weekdays"
    ADD FOREIGN KEY (weekday)
    REFERENCES public."Weekdays" (weekday) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Matches"
    ADD FOREIGN KEY (operator_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Matches"
    ADD FOREIGN KEY (offer_id)
    REFERENCES public."Offers" (offer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Offers"
    ADD FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Offers"
    ADD FOREIGN KEY (client_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Offers"
    ADD FOREIGN KEY (offer_type)
    REFERENCES public."Offer_Types" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Offer_Parameters"
    ADD FOREIGN KEY (offer_id)
    REFERENCES public."Offers" (offer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Offer_Parameters"
    ADD FOREIGN KEY (parameter_id)
    REFERENCES public."Parameters" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Type_Parameters"
    ADD FOREIGN KEY (type_name)
    REFERENCES public."Offer_Types" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Type_Parameters"
    ADD FOREIGN KEY (parameter_name)
    REFERENCES public."Parameters" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
